sequence-toolbox/SeQUeNCe

src/kernel/quantum_manager.py
fixes a possible bug with bell state measurement
=> Add support for amplitude input in quantum manager

src/components/bsm.py, src/entanglement_management/generation.py, src/entanglement_management/purification.py, src/kernel/quantum_manager.py, src/kernel/timeline.py, tests/entanglement_management/test_generation.py, tests/network_management/test_reservation.py, tests/resource_management/test_resource_manager.py
Merge updates to entanglement generation into RnD branch
=> Generation changes

tests/entanglement_management/test_purification.py
- Fixed purification test bugs: psi_minus_psi_minus case and `complex_array_equal`
- Restyled constant variables
- Replaced magic numbers and strings
@Alex-Kolar
@xwu64 
@acbarnett 
@nikoaliro
=> Fix test purification bugs

src/components/beam_splitter.py, src/components/bsm.py, src/components/detector.py, src/components/interferometer.py, src/components/light_source.py, src/components/memory.py, src/components/optical_channel.py, src/components/photon.py, src/components/spdc_lens.py, src/kernel/entity.py, src/resource_management/resource_manager.py, src/topology/node.py, src/utils/quantum_state.py, tests/components/test_detector.py, tests/entanglement_management/test_generation.py
Add random number generator to each node
=> Node generator

src/network_management/reservation.py
- Refactor file to create new methods and variables
@Alex-Kolar
@xwu64 
@acbarnett 
@kinetic-cipher
@nikoaliro
=> Extract into new methods and variables

src/network_management/reservation.py
Reverts sequence-toolbox/SeQUeNCe#65
seems some unit tests could not pass. Please check.
You can use `make test` to test all unit tests. 
```
______________ ERROR collecting tests/app/test_random_request.py _______________
tests/app/test_random_request.py:1: in <module>
from sequence.app.random_request import RandomRequestApp
/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/sequence/app/random_request.py:16: in <module>
from ..topology.node import QuantumRouter
/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/sequence/topology/node.py:30: in <module>
from ..network_management.network_manager import NewNetworkManager
/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/sequence/network_management/network_manager.py:15: in <module>
from …
```
=> Revert "Extract into new methods and variables"

mpi_tests/p_ring.py, mpi_tests/p_ring_async.py, mpi_tests/qm_server.py, src/kernel/p_quantum_manager.py, src/kernel/p_timeline.py, src/kernel/quantum_manager.py, src/kernel/quantum_manager_client.py, src/kernel/quantum_manager_server.py, src/utils/communication.py
Merge quantum manager server single-process functionality into parallel branch (found to have best performance)
=> Single process server

mpi_tests/sequential_ring.py, src/components/bsm.py, src/components/detector.py, src/components/memory.py, src/entanglement_management/purification.py, src/entanglement_management/swapping.py, src/kernel/p_quantum_manager.py, src/kernel/quantum_manager.py, src/kernel/quantum_manager_client.py, src/kernel/quantum_manager_server.py, tests/kernel/test_quantum_manager.py, tests/kernel/test_quantum_manager_server.py
Moving all random number generation to network nodes
=> Random sync

docs/source/tutorial/chapter2/hardware.md
=> change hardware.md

docs/source/tutorial/chapter3/entangle.md
=> change entangle.md

docs/source/tutorial/chapter3/entangle.md
=> change entangle.md example 2

docs/source/tutorial/chapter3/example3.py
=> change chapter 3 example3.py

docs/source/tutorial/chapter4/resource_management.md
=> change resource_management.md

src/kernel/timeline.py, tests/kernel/test_timeline.py
Refactor `Timeline` and `test_timeline.py` with test setup and adding constants to replace magic numbers and strings. This update also simplifies the tests since the loops were unnecessary.
@Alex-Kolar 
@xwu64 
@acbarnett
@kinetic-cipher
@nikoaliro
@tiroffp
=> [NO-JIRA] Refactor timeline and its tests

docs/source/tutorial/chapter1/discrete-event-simulation.md, src/components/memory.py, tests/components/test_memory.py
Merging updated AFC memory class into hardware standard branch
=> AFC memory updates

src/kernel/quantum_manager.py, src/kernel/timeline.py
instead of string "ket_vector" and "density_matrix"
=> use KET_STATE_FORMALISM and DENSITY_MATRIX_FORMALISM 

src/components/bsm.py, src/components/interferometer.py, src/kernel/entity.py, src/kernel/timeline.py, tests/components/test_bsm.py, tests/entanglement_management/test_generation.py, tests/entanglement_management/test_purification.py, tests/entanglement_management/test_swapping.py, tests/kernel/test_timeline.py, tests/topology/test_topology.py
Change Timeline.entities from a list to a dictionary;
Add functions Timeline.remove_entity_by_name and Timeline.get_entity_by_name;
Initialize the name of detectors on BSM and the name of Interferometer;
Fix errors in tests
=> Change timeline entities data structure

src/components/bsm.py, src/components/memory.py, src/entanglement_management/purification.py, src/entanglement_management/swapping.py, src/kernel/quantum_manager.py, src/topology/node.py, tests/entanglement_management/test_generation.py, tests/entanglement_management/test_purification.py, tests/entanglement_management/test_swapping.py, tests/kernel/test_quantum_manager.py, tests/network_management/test_reservation.py
1. Use the random number provided by the caller of function `QuantumManager.run_circuit` to select the state after measurement.
2. Update usage of function  `QuantumManager.run_circuit`  in files "memory.py", "generation.py", "purification.py" and "swapping.py"
2. Remove attribute QuantumManager.formalism
3. Add functions "Node.set_seed" and "Node.get_generator"
4. Add attribute "Node.seed"
5. Set seeds of nodes in unit tests
=> Quantum manager use given random number

src/network_management/network_manager.py, src/network_management/routing.py
Add function `__str__` for `StaticRoutingMessage` and`NetworkManagerMessage`
=> Add __str__ for message classes

src/components/photon.py, tests/components/test_photon.py
Add function `Photon.add_loss` and unit test;
Add typing after variables
=> Add function `Photon.add_loss` and unit test

.github/workflows/main.yml
Rewriting the github workflow code to work with MPI and mpi4py
=> MPI workflow

requirements.txt, src/topology/topology.py
We have change to json, so we should remove json5 from requirements file.
=> Remove json5

README.md, src/components/mirror.py, tests/components/test_mirror.py
=> Create mirror.py 

docs/source/references/components/mirror.rst, docs/source/references/components/top.rst, src/components/mirror.py, tests/components/test_mirror.py
Some bug fixes and modifications to the existing mirror class
=> Mirror Updates

CHANGELOG.md, docs/source/conf.py, docs/source/tutorial/chapter2/example1.py, docs/source/tutorial/chapter2/hardware.md, example/random_request_network.ipynb, example/random_request_network_mod.ipynb, example/three_node_eg_ep_es.ipynb, example/two_node_eg.ipynb, setup.py, src/components/optical_channel.py
This includes all content for updating to version 0.3.2. This is mainly a bug fix and documentation update, fixing some previous issues with the tutorial and example code.
=> Version update 0.3.2

example/absorptive_experiment.py, example/absorptive_graph.py, src/components/bsm.py, src/components/light_source.py, src/components/photon.py, src/components/spdc_lens.py, src/kernel/quantum_state.py, tests/components/test_bsm.py, tests/components/test_detector.py, tests/components/test_photon.py, tests/kernel/test_quantum_state.py
Improving the code to handle quantum states in the kernel module (and closely related interfaces in the photon module)
=> Bug fixes and Error Checking

src/app/request_app.py, src/components/bsm.py, src/components/optical_channel.py, src/entanglement_management/generation.py, src/gui/app.py, src/gui/layout.py, src/gui/menus.py, src/gui/run_gui.py, src/topology/node.py, src/topology/qkd_topo.py, src/topology/router_net_topo.py, src/topology/topology.py, tests/components/test_bsm.py, tests/topology/qkd_net_topo_sample_config.json, tests/topology/router_net_topo_sample_config.json, tests/topology/test_router_net_topo.py
This pull includes some important bug fixes to the GUI, additions to the Topology class, and bug fixes for some component models.
=> Topology updates

src/gui/app.py, src/gui/default_templates.json, src/gui/layout.py, src/gui/menus.py, src/gui/simulator_bindings.py, src/gui/user_templates.json, tests/kernel/test_quantum_state.py
Once again doing a round of bug fixes. This time in preparation for our tutorial at IEEE QCE 2023.
=> GUI Bug Fixes

docs/source/tutorial/chapter4/resource_management.md, docs/source/tutorial/chapter4/two_flow.py, docs/source/tutorial/chapter5/network_manager.md, docs/source/tutorial/chapter6/application.md, docs/source/tutorial/chapter6/custom_app.py
Hi SeQUeNCe team,
I went through the tutorial Chapter 4,5,6 and fixed some minor issues, including:
1. Minor text and code issues in the Readme file
2. Minor code issues in the Python file
Thanks,
Caitao Zhan
=> Tutorial minor fix in Chapter 4,5,6

tests/README.md, tests/entanglement_management/test_purification.py
This PR updates the `test/test_purification.py` and has carefully taken care of an [old pull request from Lester Kim](https://github.com/sequence-toolbox/SeQUeNCe/pull/64)
=> [Minor] update test/test_purification.py

.gitignore, docs/source/tutorial/chapter5/network_manager.md
=> [minor] update tutorial chapter 5

.gitignore, src/network_management/reservation.py, tests/network_management/test_reservation.py, tests/resource_management/test_resource_manager.py
This pull request takes care of an old pull request #73
=> [minor] take care of pull request #73

sequence/components/bsm.py, sequence/components/memory.py, sequence/components/optical_channel.py, sequence/components/photon.py, sequence/kernel/quantum_manager.py, sequence/kernel/quantum_state.py, sequence/kernel/timeline.py, sequence/network_management/reservation.py, sequence/resource_management/memory_manager.py, sequence/resource_management/rule_manager.py, sequence/topology/node.py, sequence/topology/router_net_topo.py, sequence/topology/topology.py, sequence/utils/config_generator.py, sequence/utils/encoding.py, tests/components/test_photon.py
Adding a Quantum Manager for the Bell Diagonal State. Note that this PR does not include Single Heralded entanglement generation, swapping, and purification protocols based on the Bell Diagonal State.
=> [Major] Add Quantum Manager for Bell Diagonal State

.github/workflows/main.yml, requirements.txt, sequence/app/random_request.py, sequence/components/bsm.py, sequence/components/circuit.py, sequence/components/detector.py, sequence/kernel/quantum_manager.py, sequence/utils/config_generator.py, tests/components/test_circuit.py, tests/components/test_fiber_stretcher.py
Supports the newest version of Numpy(2.2), SciPy(1.4), and QuTiP(5.0)
=> [major] Add support for Python 3.13 and remove support for Python 3.9

LICENSE, docs/source/tutorial/chapter2/hardware.md, sequence/components/memory.py, sequence/components/optical_channel.py, sequence/kernel/timeline.py, sequence/topology/node.py
This pull request includes changes to improve the handling of distance and decoherence rate calculations in the `sequence/components` module. The most important changes include updating the data type for distance from `int` to `float` and refining the calculation for decoherence rate to handle zero coherence time.
Improvements to distance handling:
* [`sequence/components/optical_channel.py`](diffhunk://#diff-86187dd21766e49ff87b34801edef5734e5b4d03508b37a5d5340b3d8be2956dL33-R46): Updated the data type for `distance` from `int` to `float` in `OpticalChannel`, `QuantumChannel`, and `ClassicalChannel` classes, and their respective constructors and methods. [[1]](diffhunk://#diff-86187dd21766e49ff87b34801edef5734e5b4d03508b37a5d5340b3d8be2956dL33-R46) …
=> Revisions to tutorial related code

docs/source/tutorial/chapter3/example3.py, sequence/utils/noise.py, tests/utils/test_noise.py
- added `Noise` class which has methods that simulate depolarization and measurement noise
- added 3 new test cases in `test_noise.py`
=> [major] noise.py and test_noise.py

sequence/utils/noise.py, tests/utils/test_noise.py
Elaborated docstrings of noise.py methods. Explained how depolarization method supposed to be used and polished measurement noise docstring.
=> Docstring Updated `noise.py

sequence/components/bsm.py, sequence/components/optical_channel.py, sequence/entanglement_management/generation.py, sequence/resource_management/resource_manager.py, tests/resource_management/test_resource_manager.py
Brings over changes from quisp collab branch
=> 226 fix protocol delay

.github/workflows/development.yml, .github/workflows/publish.yml
=> Cicd pipeline

.github/workflows/development.yml, sequence/entanglement_management/generation/single_heralded.py
Patches the bug where SH entanglement generation has a significant delay compared to theoretical expected value.
=> Single Herald Entanglement Generation Patch
